
package maze.domain;

/**
 * A class that uses the different maze generating classes.
 * @author taleiko
 */
public class MazeGenerator {
    private RecursiveBacktracker recursiveBacktracker;
    private KruskalMaze kruskal;

    /**
     * Initializes the recursive backtracker class with its width and height.
     * @param mazeWidth
     * @param mazeHeight 
     */
    public void initializeRecursiveBacktracker(int mazeWidth, int mazeHeight) {
        recursiveBacktracker = new RecursiveBacktracker(mazeWidth, mazeHeight);
    }
    /**
     * Initializes the Kruskal maze generator with its width and height.
     * @param mazeWidth
     * @param mazeHeight
     */
    public void initializeKruskal(int mazeWidth, int mazeHeight) {
        kruskal = new KruskalMaze(mazeWidth, mazeHeight);
    }
    /**
     * Tells the recursive backtracker class to generate a maze.
     */
    public void generateRecursiveBacktrackerMaze() {
        recursiveBacktracker.generateMaze();
    }
    /**
     * Tells the Kruskal class to generate a maze.
     */
    public void generateKruskalMaze() {
        kruskal.generateMaze();
    }
    /**
     * Returns the maze generated by the recursive backtracker class.
     * @return generatedMaze
     */
    public char[][] getRecursiveBacktrackerMaze() {
        return recursiveBacktracker.getMaze();
    }
    
    public char[][] getKruskalMaze() {
        return kruskal.getMaze();
    }
}
